# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f49c8dc5b79f6489ca80f66f1fcc673"
name = "Countdown Timer"
application_url = "https://ellen-opinion-century-soccer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://ellen-opinion-century-soccer.trycloudflare.com/api/auth/callback" ]

[app_proxy]
url = "https://ellen-opinion-century-soccer.trycloudflare.com/api/storefront"
subpath = "countdown"
prefix = "apps"